
<tr valign="top">
<td bgcolor="#ffffff" width="191"><table width="181">
<tr><td><a href="1.htm"><img src="https://hss.nuu.edu.tw/var/file/20/1020/plugin/mobile/title/hln_2805_7365018_05613.jpg"></a></td></tr>
<tr><td><a href="1.htm"><img src="https://hss.nuu.edu.tw/var/file/20/1020/plugin/mobile/title/hln_2808_7596863_06584.png"></a></td></tr>
<tr><td><a href="1.htm"><img src="https://hss.nuu.edu.tw/var/file/20/1020/plugin/mobile/title/hln_2813_3364493_07080.jpg"></a></td></tr>
</table></td>

<td bgcolor="#ffffff"width="806"><table width="800">
<tr>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBzUFLe9uLcpTD0pcjIS_pUfYQHsYxQ5rONcohvZ2B2ZOPDz6F&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5qagzjRKwo8PDoLHBoeeUso8NHqiMO0FuzrA1lXKsK07D9Gfc&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoitPhGJ9kXN_LDzVxfsr5-DdZDCtLiojmL2G1OnAvYxatQ6c&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRnAySrbWVxop-arAyIbhxRmzMxwsJmUQfU9Ui0vIbpJ8IgQze&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuv82Zraue9KU5sf8xkNl99ILSyVp76hxWX1_6qTMMZrwdXbA&s"></td>

</tr>

<td align="center"><a href="1.htm"target="_blank">第一個作品</td>
<td align="center"><a href="1.htm"target="_blank">第二個作品</td>
<td align="center"><a href="1.htm"target="_blank">第三個作品</td>
<td align="center"><a href="1.htm"target="_blank">第四個作品</td>
<td align="center"><a href="1.htm"target="_blank">第五個作品</td>
</tr>



<tr>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM70Aku9izlING_mXuEenDamBPnwCvWnNgPhcPH7I5A0UoNQIu&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScnH-8uBSoINB9KT-1XXLLkXHAKE-LfpFpu_m7NjF33BNZVag&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFdHR2bRNMd1Pz2kIagWxNgn1YQMiLS_-PiIkyeGxppITefn8&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1Oh6llNTYNGqVyOAHGSVSqRAC2jajUXsF2lO2sj9VY5yub4M&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE12ZCIBddM8-fHeJ-EhM_iddxgdZo39RDH5Loq4GoUZBvskg&s"></td>

</tr>

<td align="center"><a href="1.htm"target="_blank">第六個作品</td>
<td align="center"><a href="1.htm"target="_blank">第七個作品</td>
<td align="center"><a href="1.htm"target="_blank">第八個作品</td>
<td align="center"><a href="1.htm"target="_blank">第九個作品</td>
<td align="center"><a href="1.htm"target="_blank">第十個作品</td>
</tr>




<tr>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTl1LG0ovmd6umNvGqii_JVDXsZMZRfFefS2ucKGoAukkEJq1gX&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQIkhGOarA_bRK-dEeuJiHW9UpEX8fXYm1su4aw9dcn5DGvWMd&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJ4KhOx4aMDKqi19b-E7Xb3-d-MinrK57RFm-SwCWIUG2MywxE&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdH5SmJO-5CC63A2Fr8HqVNoQT4InVrZR-o68SMOw5t4LUlO0&s"></td>
<td><img width="145" height="200"src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpgjZPcPZW1wB-ppaDo_3zNmIxlLfzyRHRto09iDPVLATJu5U&s"></td>

</tr>

<td align="center"><a href="1.htm"target="_blank">第十一個作品</td>
<td align="center"><a href="1.htm"target="_blank">第十二個作品</td>
<td align="center"><a href="1.htm"target="_blank">第十三個作品</td>
<td align="center"><a href="1.htm"target="_blank">第十四個作品</td>
<td align="center"><a href="1.htm"target="_blank">第十五個作品</td>
</tr>

</table></td>
</tr>
</table>


</div>
</body>

<br/>
<div id="bottom">
  <table width="1000" border="0" cellpadding="0" cellspacing="1" bgcolor="#999999">
    <tr>
      <td align="center" bgcolor="#FFFFFF"><br />
        &copy版權所有。國立聯合大學文創系。禁止複製<br/>
          <br />
        </a></td>
    </tr>
  </table>
</div>


</html>
